### ISSUE TITLE
Provide googleTokenLogin got error

### ISSUE THREAD

**Issue by justmealf** [devbaji/vue3-google-login#41]
Hi i try to provide googleTokenLogin following the docs, got some error after installing 'google-auth-library' 

`TypeError: Class extends value undefined is not a constructor or null
    at node_modules/agent-base/dist/index.js (index.ts:29:42)
    at __require2 (chunk-2LSFTFF7.js?v=3d02b4e8:19:50)
    at node_modules/https-proxy-agent/dist/index.js (index.ts:7:1)
    at __require2 (chunk-2LSFTFF7.js?v=3d02b4e8:19:50)
    at node_modules/gaxios/build/src/gaxios.js (gaxios.ts:32:1)
    at __require2 (chunk-2LSFTFF7.js?v=3d02b4e8:19:50)
    at node_modules/gaxios/build/src/index.js (index.ts:15:1)
    at __require2 (chunk-2LSFTFF7.js?v=3d02b4e8:19:50)
    at node_modules/gcp-metadata/build/src/index.js (index.ts:8:1)
    at __require2 (chunk-2LSFTFF7.js?v=3d02b4e8:19:50)`

Google pop up auth shown normally, but i need access user email, name and image profile. There's way to provide that without using 'google-auth-library' ?

**Comment by devbaji** [comment]
@justmealf Looks like an error in one of your npm packaages, please re-open if you are sure that this error is from vue3-google-login package
